version: "3.9"
services:

  rates_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["bash", "./start.sh"]
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_PORT=5432
      - DB_DRIVER=postgres
      - DB_NAME=postgres

  db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: